### ISSUE TITLE
Is this more library like

### ISSUE THREAD

**Issue by Defragster** [FrankBoesing/SPIFFStest#1]
[spiffs.zip](https://github.com/FrankBoesing/SPIFFStest/files/4209503/spiffs.zip)

until it had 'library.properties' it didn't see it as a library.  That file needs to be edited - I copied from greiman/SdFat-beta

Moved example to a folder 
Called it spiffs to match spiffs.h
Put other non-Sketch stuff in EXTRAS

**Comment by Defragster** [comment]
Doesn't always work each time - maybe a NAND miscalc?

mount res: 0
--> Test Start ...
--> Hllo World! abcDEF <--
--> ... Test End.

versus 2nd upload:
mount res: 0
--> Test Start ...
--> Hello World! abcDEF <--
--> ... Test End.

**Comment by FrankBoesing** [comment]
As said - I think it's a serial monitor problem.
We could add larger files and do a CRC to check for errors.

**Comment by FrankBoesing** [comment]
You've got access - feel free to upload your zip.

**Comment by Defragster** [comment]
Upload ZIP - I just rewrote the whole tree :)

**Comment by Defragster** [comment]
If the problem is SerMon - it made the same mistake twice ?
mount res: 0
--> Test Start ...
--> HeHlo World! abcDEF <--
--> ... Test Middle ... 
--> HeHlo World! abcDEF <--
--> ... Test End.

code:
static void test_spiffs() {
  char buf[512] = "Hello World! abcDEF";
  Serial.printf("--> Test Start ...\n");

  // Surely, I've mounted spiffs before entering here
  int szLen = strlen( buf );
  spiffs_file fd = SPIFFS_open(&fs, "my_file", SPIFFS_CREAT | SPIFFS_TRUNC | SPIFFS_RDWR, 0);
  if (SPIFFS_write(&fs, fd, (u8_t *)buf, szLen) < 0) Serial.printf("errno %i\n", SPIFFS_errno(&fs));
  SPIFFS_close(&fs, fd);
  strcpy( buf, "xxxxxx");
  fd = SPIFFS_open(&fs, "my_file", SPIFFS_RDWR, 0);
  if (SPIFFS_read(&fs, fd, (u8_t *)buf, szLen) < 0) Serial.printf("errno %i\n", SPIFFS_errno(&fs));
  SPIFFS_close(&fs, fd);

  Serial.printf("--> %s <--\n", buf);
  Serial.printf("--> ... Test Middle ... \n");
  Serial.printf("--> %s <--\n", buf);
  Serial.printf("--> ... Test End.\n");
}

**Comment by FrankBoesing** [comment]
Works for me...
void setup() {
  while (!Serial);
  my_spiffs_mount();
  test_spiffs();
  test_spiffs();
  test_spiffs();
  test_spiffs();  
}

mount res: 0
--> Test Start ...
--> Hello World! abcDEF <--
--> ... Test Middle ... 
--> Hello World! abcDEF <--
--> ... Test End.
--> Test Start ...
--> Hello World! abcDEF <--
--> ... Test Middle ... 
--> Hello World! abcDEF <--
--> ... Test End.
--> Test Start ...
--> Hello World! abcDEF <--
--> ... Test Middle ... 
--> Hello World! abcDEF <--
--> ... Test End.
--> Test Start ...
--> Hello World! abcDEF <--
--> ... Test Middle ... 
--> Hello World! abcDEF <--
--> ... Test End.

???

**Comment by Defragster** [comment]
Doing a better test …

Just saw this: 
mount res: 0
--> Test Start ...
errno -10004
--> xxxxxx <--
--> ... Test Middle ... 
xxxxxx
--> ... Test End.

**Comment by FrankBoesing** [comment]
Which chip do you use? Is it OK?

**Comment by Defragster** [comment]
Got this on 7th UPLOAD after code change:
mount res: 0
--> Test Start ...
--> @@Hlo World! What a wonderful World :) <--
--> ... Test Middle ... 
--> [Bad #0==@|40][Bad #1==@|40][Bad #2==H|48]lo World! What a wonderful World :) <--
--> ... Test End.

CODE: … updated in a sec

**Comment by Defragster** [comment]
WINBOND 16 MB { _128_ }. Never saw it fail before – not used much.

**Comment by FrankBoesing** [comment]
Can you try the SerialFlash library (by Paul)?

**Comment by FrankBoesing** [comment]
Your example works for me...
mount res: 0
--> Test Start ...
--> Hello World! What a wonderful World :) <--
--> ... Test Middle ... 
--> Hello World! What a wonderful World :) <--
--> ... Test End.

**Comment by Defragster** [comment]
Try it with 10 Uploads in a row?
My day here is done.  

Erase Everything worked and hardware Test:
Raw SerialFlash Hardware Test
Read Chip Identification:
  JEDEC ID:     EF 40 18
  Part Nummber: W25Q128FV
  Memory Size:  16777216 bytes
  Block Size:   65536 bytes

Reading Chip...
Writing 8192 signatures
Double Checking All Signatures:
  all 8192 signatures read ok

Checking Signature Pairs
  all 4095 signature pairs read ok

Checking Read-While-Write (Program Suspend)
  write 256 bytes at 256
  write time was 375 microseconds.
  read-while-writing: 00 00 00 00 15 F5 95 4B 
  test passed, good read while writing

Checking Read-While-Erase (Erase Suspend)
  erase time was 221490 microseconds.
  erase correctly erased 65536 bytes
  read-while-erasing: 00 00 00 00 15 F5 95 4B 
  test passed, good read while erasing
All Tests Passed  :-)

Test data was written to your chip.  You must run
EraseEverything before using this chip for files.

**Comment by Defragster** [comment]
Did this after hHardWare test and it worked FOUR times - then the FIFTH upload did this.

I am getting errors from somewhere ... I saw something like this before and I just saw it again:
mount res: 0
--> Test Start ...
errno -10010
--> xxxxxx <--
--> ... Test Middle ... 
--> [Bad #0==x|78][Bad #1==x|78][Bad #2==x|78][Bad #3==x|78][Bad #4==x|78][Bad #5==x|78] <--
--> ... Test End.

**Comment by FrankBoesing** [comment]
I've uploaded a little bugfix. But this was not responsible for your problem.
I'm going to stress it a little bit and write in a loop. 100 times ok?

**Comment by FrankBoesing** [comment]
for (int i = 0; i<100; i++) {
  test_spiffs();
  }

All ok.
  for (int i = 0; i<100; i++) {
  test_spiffs();
  }

**Comment by FrankBoesing** [comment]
As we have the same software, your hardware must be the problem.

**Comment by Defragster** [comment]
Perhaps so - I ran with 100 loops added fine 3 times and then it failed 4 on the next 100.

That is a Rev B Audio.

I have a REV D board - that doesn't work at all - even SerialFlash test above - with SDCS set to 10.

zzzZz

**Comment by FrankBoesing** [comment]
Good night.
Tested a T3.6 with the winbond flsh you have.
No Problems...

**Comment by FrankBoesing** [comment]
[spiffstest.ino.TEENSY40.zip](https://github.com/FrankBoesing/SPIFFStest/files/4209801/spiffstest.ino.TEENSY40.zip)
Please try the attached hex-file

**Comment by FrankBoesing** [comment]
I've added test for internal flash. Teensy deletes it on upload :(
We have to check if we need a sync()!!

**Comment by Defragster** [comment]
I get this output:
mount res: 0
--> Test Start ...
--> Hello World! What a wonderful World :) <--
--> ... Test Middle ... 
--> Hello World! What a wonderful World :) <--
--> ... Test End.
--> Test Start ...
--> Hello World! What a wonderful World :) <--
--> ... Test Middle ... 
--> Hello World! What a wonderful World :) <--
--> ... Test End.
--> Test Start ...
--> Hello World! What a wonderful World :) <--
--> ... Test Middle ... 
--> Hello World! What a wonderful World :) <--
--> ... Test End.
--> Test Start ...
--> Hello World! What a wonderful World :) <--
--> ... Test Middle ... 
--> Hello World! What a wonderful World :) <--
--> ... Test End.
--> Test Start ...
--> Hello World! What a wonderful World :) <--
--> ... Test Middle ... 
--> Hello World! What a wonderful World :) <--
--> ... Test End.

**Comment by FrankBoesing** [comment]
thanks :) was that with the hex-file ?
In this case something is wrong in your installation - may buggy SPI or other problem...

**Comment by Defragster** [comment]
That was the HEX file output.

My Rev B system not showing errors now with the code just updated on GitHub

And the Rev D T4 works with Flash CS 6!  I did add flux and solder on the flash pins, then alcohol wash and it is working - it was probably just needing the right CS.

**Comment by Defragster** [comment]
Running the NEW example : internal_flash on another T4 I get this:
SPIFFS filesystem starts at: 0x60010000

mount res: 0
--> Test Start ...
--> Hello World! What a wonderful World :) <--
--> ... Test Middle ... 
--> --> xxxxxx <--
--> ... Test Middle ... 
--> --> Hello World! What a wonderful World :) <--
--> ... Test Middle ... 
--> Hello World! What a wonderful World :) <--
--> ... Test End.

**Comment by Defragster** [comment]
Spiffs works as library - two examples -
